#!/bin/bash
set -euo pipefail

mkdir -p build/linux
cp -f build/Makefile.linux build/linux/Makefile

cd build/linux

# Install prereqs based on https://github.com/apache/parquet-cpp#linux
sudo apt-get install libboost-dev libboost-filesystem-dev \
  libboost-program-options-dev libboost-regex-dev \
  libboost-system-dev libboost-test-dev \
  libssl-dev libtool bison flex pkg-config

# Install prereqs based on https://github.com/apache/arrow/tree/master/cpp
sudo apt-get install cmake \
  libboost-dev \
  libboost-filesystem-dev \
  libboost-system-dev

if [ ! -e ../../sqlite/sqlite3 ]; then
  make sqlite
fi

if [ "$(lsb_release -s -r)" == "16.04" ]; then
  export ICU_VERSION=55.1
elif [ "$(lsb_release -s -r)" == "18.04" ]; then
  export ICU_VERSION=60.2
else
  echo "unsure what libicu version to use" >&2
  exit 1
fi

export ICU_VERSION_U=${ICU_VERSION//./_}
make "$@"
