#!/bin/bash
set -euo pipefail

echo "CC is ${CC:-unknown}"
echo "CXX is ${CXX:-unknown}"

export CC=gcc
export CXX=g++
sudo apt-get install software-properties-common
sudo add-apt-repository --yes ppa:george-edison55/cmake-3.x
sudo apt-get update
PREBUILT=1 ./make-linux
