#!/bin/bash

set -euo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"
make


if [ ! -v DEBUG ]; then
  ../sqlite/sqlite3 -init ./cmds.txt < /dev/null
else
  gdb -ex run --args ../sqlite/sqlite3 -init ./cmds.txt
fi

