#!/bin/bash

set -euo pipefail
#set -x

PARQUET_CPP=${PARQUET_CPP:-~/src/parquet-cpp}

# make obj file
clean() {
  rm -f *.o *.so
}

build() {
  clean
  # -O3 -s -DNDEBUG
  g++ -O3 -std=c++11 -Wall -fPIC -c -g *.cc -I ../sqlite -lz -ldl -lpthread 

  g++ -O3 -shared -o libparquet.so *.o \
    ${PARQUET_CPP}/build/release/libparquet.a \
    ${PARQUET_CPP}/thrift_ep/src/thrift_ep-install/lib/libthrift.a \
    ${PARQUET_CPP}/build/release/libarrow.so \
    /usr/lib/x86_64-linux-gnu/libboost_regex.so
}

fn=${1:-build}

"$fn"
